### ISSUE TITLE
GATT Transport (GT)

### ISSUE THREAD

**Issue by RussNelson** [PunchThrough/bean-documentation#2]
The GATT Transport (GT) description should call its "Header" a "GT Header" and should explicitly make reference to the following section. You'd think that saying "Header" in the "GT" section should be a clue, but better to explicitly spell it out. This *is* reference documentation, and a bit of redundancy for exactness is appropriate.

**Comment by mplewis** [comment]
I agree. I clarified this in v0.3.2—take a look now and let me know what you think.

**Comment by RussNelson** [comment]
I see a reference to a GT message: "each new GT Message (0, 1, 2, 3, 0, ...)" yet no such thing is defined. Could that realy be "GST Message"? Otherwise, yes, this is clearer.
